# Input files to compare
input_file_1: input/input.csv
input_file_2: input/input2_offset.csv



# Header cleanup
header_cleanup:
  - "Ave. (C)"
  - "(C)"




# Time alignment
# Options:
#   aligh
#   manual_offset_s: 5.0 → shift second file by 5 seconds
alignment_method: rising_edge # "rising_edge" or "peak_detection" or "manual"

auto_align_column_file1: 3      # Column from File 1 to use for auto-alignment.
                                      # column index (integer).
                                      # Defaults to column index 1 if not specified.

auto_align_column_file2: 3      # Column from File 2 to use for auto-alignment.


manual_offset_s: -6.2 # Ignored if auto_align is true

# Columns to plot (indices, excluding time/sample column)
columns_to_plot: []


# Sampling rate in milliseconds
sampling_interval_ms: 100

# Plot formatting options (default settings)
plot_format:
  size:
    width: 12
    height: 7.5
  font_sizes:
    axis: 14
    title: 16
    legend: 12
    ticks: 12
  grid:
    major:
      color: "#00000000"
      linestyle: ":"
      linewidth: 0.8
    minor:
      color: "#A8A8A8C8"
      linestyle: ":"
      linewidth: 0.5
  axis_labels:
    x: "Time [s]"
    y: "Temperature [°C]"
  plot_title: "Title of the Plot"

# Time window to display [start_s, end_s]
time_window: []

# Output formats
save_formats: ["jpeg"]
output_dir: output
